CFLAGS=		-Os -std=c89 -w -melks -mcmodel=small -march=i8088 $(DEFS)
CC=		ia16-elf-gcc
APPEND=		.elks

fish: src/fish.c
	$(CC) $(CFLAGS) -o bin/fish$(APPEND) src/fish.c

morse: src/morse.c
	$(CC) $(CFLAGS) -o bin/morse$(APPEND) src/morse.c

number: src/number.c
	$(CC) $(CFLAGS) -o bin/number$(APPEND) src/number.c

arithmetic:
	@echo "Sorry, but arithmetic does not currently work on ELKS."
	@echo "See Github issue #1 for more info."

ppt: src/ppt.c
	$(CC) $(CFLAGS) -o bin/ppt$(APPEND) src/ppt.c

banner: src/banner.c
	@echo "ELKS already has a banner program built-in as of 0.9.1."
	@echo "This banner program is for if you have a paper terminal"
	@echo "and you want really big banners on physical paper."
	@echo "The built-in ELKS banner is much more akin to figlet."
	@echo " "
	$(CC) $(CFLAGS) -o bin/banner$(APPEND) src/banner.c

clean:
	rm -f bin/*$(APPEND)
